//! # mcpg-plugin-backend-llm-stability
//!
//! Stability AI Stable Image (v2beta) image-generation binding plugin
//! for MCPG.
//!
//! Ships one [`BackendPlugin`] instance:
//!
//! - [`StabilityImagePlugin`] (`kind: "stability.image"`) — POSTs
//!   multipart/form-data to
//!   `https://api.stability.ai/v2beta/stable-image/generate/{model_route}`
//!   where `model_route` ∈ {`core`, `sd3`, `ultra`}.
//!
//! This is the third image-generation partner in the first-party
//! plugin set after `mcpg-plugin-backend-llm-openai` (DALL-E /
//! Azure OpenAI image) and `mcpg-plugin-backend-llm-gemini` (Imagen).
//!
//! Generated bytes are pushed into the gateway's `ContentStore` by
//! the shared [`mcpg_backend_llm_shared::ImageEngine`]; the binding
//! response carries `mcpg-resource://<id>` URIs rather than inline
//! base64 blobs.
//!
//! [`BackendPlugin`]: mcpg_plugin_protocol::BackendPlugin

/// cdylib sync bridge + `declare_plugin!` export (backend-plugin-migration).
/// Additive: the gateway keeps using the static `new()` path. The
/// `mcpg_plugin_register` FFI symbol is gated behind the `cdylib-export`
/// feature inside the macro expansion. Public so the wrapper types +
/// macro-generated entity modules are part of the crate's public surface
/// (mirrors the openai / anthropic conversions + the nats / kafka pilots,
/// which keep their bridges at crate root) — this also keeps the wrappers
/// from tripping `dead_code` on the default rlib build where neither
/// `cdylib-export` nor `static-firstparty` references them.
pub mod cdylib;
mod config;
mod image_adapter;
mod image_plugin;

pub use config::StabilityImageSpec;
pub use image_adapter::StabilityImageAdapter;
pub use image_plugin::StabilityImagePlugin;
